import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    en: {
        appName: 'Fee Management',
        logout: 'Logout',
        dashboard: 'Dashboard',
        students: 'Students',
        monthlyCollection: 'Monthly Collection',
        yearlyReport: 'Yearly Report',
        aiAnalytics: 'AI Analytics',
        smsReminders: 'SMS Reminders',
        addStudent: 'Add Student',
        collectFee: 'Collect Fee',
        pendingFees: 'Pending Fees',
        profile: 'Profile',
        edit: 'Edit',
        search: 'Search',
        rollNo: 'Roll No',
        name: 'Name',
        class: 'Class',
        mobile: 'Mobile',
        amount: 'Amount',
        status: 'Status',
        paid: 'Paid',
        pending: 'Pending',
        action: 'Action',
        backToDashboard: 'Back to Dashboard',
        welcomeBack: 'Welcome back',
        totalStudents: 'Total Students',
        totalCollected: 'Total Collected',
        totalMonthlyCollection: 'Total Monthly Collection',
        avgPayment: 'Avg. Payment',
        paymentDate: 'Payment Date',
        downloadReport: 'Download Report',
        exportData: 'Export Data',
        selectLanguage: 'Select Language',
        english: 'English',
        hindi: 'Hindi',
        marathi: 'Marathi',
        admin: 'Admin',
        student: 'Student',
        quickActions: 'Quick Actions',
        reports: 'Reports',
        history: 'History',
        payNow: 'Pay Now',
        payFee: 'Pay Fee',
        viewProfile: 'View Profile',
        editProfile: 'Edit Profile',
        login: 'Login',
        overview: 'Overview of student fee management system',
        viewCompleteFeeRecords: 'View your complete fee payment records',
        allStatus: 'All Status',
        paidAmount: 'Paid Amount',
        pendingAmount: 'Pending Amount',
        monthsCollected: 'Months collected',
        totalBalance: 'Total balance to be collected',
        allStudents: 'All Students',
        selectStudent: 'Select Student',
        school: 'School',
        address: 'Address',
        contact: 'Contact',
        actions: 'Actions',
        saveChanges: 'Save Changes',
        cancel: 'Cancel',
        fullName: 'Full Name',
        enterName: 'Enter student name',
        enterRollNo: 'Enter roll number',
        enterMobile: 'Enter mobile number',
        enterPassword: 'Enter password',
        newPassword: 'New Password (blank to keep current)',
        studentDetails: 'Student Details',
        deleteConfirm: 'Are you sure you want to delete this?',
        recordsDeleted: 'Records deleted successfully',
        updateSuccess: 'Updated successfully',
        failed: 'Failed to process request',
        noResults: 'No results found',
        smsSent: 'SMS reminder sent successfully',
        collectMonthlyFee: 'Collect Monthly Fee',
        recordFeePayment: 'Record fee payment from a student',
        chooseStudent: 'Choose a student',
        paymentSummary: 'Payment Summary',
        recordPayment: 'Record Payment',
        recordingPayment: 'Recording Payment...',
        paymentRecorded: 'Fee payment recorded successfully!',
        month: 'Month',
        year: 'Year',
        selectMonth: 'Select Month',
        thisMonth: 'This Month',
        registerStudentDesc: 'Register a new student in the system',
        collectFeeDesc: 'Record monthly fee payment from students',
        studentListDesc: 'See complete list of registered students',
        schoolsDesc: 'View schools and filter students by school',
        monthlyCollectionDesc: 'Track total payments and collector details',
        yearlyReportDesc: 'Generate yearly fee collection reports',
        smsRemindersDesc: 'Send fee alerts to pending students',
        recentPayments: 'Recent Payment Records',
        highestPending: 'Highest Pending Fees',
        viewMonthlyReport: 'View Monthly Report',
        viewAll: 'View All',
        aiAnalyticsTitle: 'AI Analytics Dashboard',
        aiAnalyticsDesc: 'View AI-powered insights, predictions, and payment trends',
        aiPowered: 'AI Powered',
        schools: 'Schools',
        addSchool: 'Add School',
        totalSchools: 'Total schools registered',
        verifiedSchool: 'Verified School',
        addressOptional: 'Address (Optional)',
        contactOptional: 'Contact (Optional)',
        createSchool: 'Create School',
        noSchoolsFound: 'No schools found. Add a school to get started.',
        addFirstSchool: 'Add First School',
        schoolName: 'School Name',
        pendingFeeReminders: 'Pending Fee Reminders',
        sendSmsAlerts: 'Send SMS alerts to students with outstanding balances',
        sendAllReminders: 'Send All Reminders',
        lastReminder: 'Last Reminder',
        sending: 'Sending...',
        smsSentTo: 'SMS Sent to',
        neverSms: 'Never',
        editStudentDetails: 'Edit Student Details',
        fullName: 'Full Name',
        rollNumber: 'Roll Number',
        mobileNumber: 'Mobile Number',
        newPasswordNote: 'New Password (leave blank to keep current)',
        updateStudent: 'Update Student',
        smsRemindersSent: 'SMS reminders sent successfully',
        sendSmsRemindersAllConfirm: 'Send SMS reminders to all students?',
        pendingFeesReport: 'Pending Fees Report',
        totalOutstandingBalance: 'Total Outstanding Balance',
        grandTotalPaid: 'GRAND TOTAL PAID',
        grandTotalPending: 'GRAND TOTAL PENDING',
        addNewStudent: 'Add New Student',
        registerStudentDesc: 'Register a new student and upload their QR code',
        studentAddedSuccess: 'Student added successfully!',
        failedToAddStudent: 'Failed to add student',
        selectClass: 'Select Class',
        selectSchool: 'Select School',
        new: 'New',
        enterNewSchoolName: 'Enter new school name',
        add: 'Add',
        class: 'Class',
        usernameUserID: 'Username (UserID)',
        leaveBlankForMobile: 'Leave blank to use Mobile Number',
        studentQrCode: 'Student QR Code Image',
        clickToUploadQr: 'Click to upload QR code',
        fileFormatNote: 'PNG, JPG or SVG (Max 2MB)',
        addingStudent: 'Adding Student...',
        registerStudent: 'Register Student',
        std6: '6th Std', std7: '7th Std', std8: '8th Std', std9: '9th Std', std10: '10th Std',
        yearlyFeeReport: 'Yearly Fee Report',
        academicYear: 'Academic Year',
        generatedAt: 'Generated At',
        reportType: 'Report Type',
        comprehensiveSummary: 'All Students Comprehensive Summary',
        totalYearlyPaid: 'Total Yearly Paid',
        monthsCollected: 'Months Collected',
        schoolBranding: 'OM SAI SCHOOL VAN SERVICE',
        yearlyCollectionGrid: 'Yearly Collection Grid',
        totalPendingBalance: 'TOTAL PENDING BALANCE',
        unpaid: 'Unpaid',
        for: 'for',
        totalCount: 'Total Count'
    },
    hi: {
        appName: 'फीस प्रबंधन',
        logout: 'लॉग आउट',
        dashboard: 'डैशबोर्ड',
        students: 'छात्र',
        monthlyCollection: 'मासिक संग्रह',
        yearlyReport: 'वार्षिक रिपोर्ट',
        aiAnalytics: 'एआई एनालिटिक्स',
        smsReminders: 'एसएमएस रिमाइंडर्स',
        addStudent: 'छात्र जोड़ें',
        collectFee: 'फीस जमा करें',
        pendingFees: 'बकाया फीस',
        profile: 'प्रोफ़ाइल',
        edit: 'संपादन',
        search: 'खोजें',
        rollNo: 'रोल नंबर',
        name: 'नाम',
        class: 'कक्षा',
        mobile: 'मोबाइल',
        amount: 'राशि',
        status: 'स्थिति',
        paid: 'भुगतान किया',
        pending: 'बकाया',
        action: 'कार्रवाई',
        backToDashboard: 'डैशबोर्ड पर वापस जाएं',
        welcomeBack: 'वापस स्वागत है',
        totalStudents: 'कुल छात्र',
        totalCollected: 'कुल संग्रह',
        totalMonthlyCollection: 'कुल मासिक संग्रह',
        avgPayment: 'औसत भुगतान',
        paymentDate: 'भुगतान तिथि',
        downloadReport: 'रिपोर्ट डाउनलोड करें',
        exportData: 'डेटा निर्यात करें',
        selectLanguage: 'भाषा चुनें',
        english: 'अंग्रेजी',
        hindi: 'हिंदी',
        marathi: 'मराठी',
        admin: 'एडमिन',
        student: 'छात्र',
        quickActions: 'त्वरित कार्रवाई',
        reports: 'रिपोर्ट',
        history: 'इतिहास',
        payNow: 'अभी भुगतान करें',
        payFee: 'फीस भरें',
        viewProfile: 'प्रोफ़ाइल देखें',
        editProfile: 'प्रोफ़ाइल बदलें',
        login: 'लॉगिन',
        overview: 'छात्र शुल्क प्रबंधन प्रणाली का विवरण',
        viewCompleteFeeRecords: 'अपने पूर्ण शुल्क भुगतान रिकॉर्ड देखें',
        allStatus: 'सभी स्थिति',
        paidAmount: 'भुगतान की गई राशि',
        pendingAmount: 'बकाया राशि',
        monthsCollected: 'महीने संकलित',
        totalBalance: 'कुल बकाया राशि',
        allStudents: 'सभी छात्र',
        selectStudent: 'छात्र चुनें',
        school: 'स्कूल',
        address: 'पता',
        contact: 'संपर्क',
        actions: 'कार्रवाई',
        saveChanges: 'परिवर्तन सहेजें',
        cancel: 'रद्द करें',
        fullName: 'पूरा नाम',
        enterName: 'छात्र का नाम दर्ज करें',
        enterRollNo: 'रोल नंबर दर्ज करें',
        enterMobile: 'मोबाइल नंबर दर्ज करें',
        enterPassword: 'पासवर्ड दर्ज करें',
        newPassword: 'नया पासवर्ड (पुराना रखने के लिए खाली छोड़ें)',
        studentDetails: 'छात्र विवरण',
        deleteConfirm: 'क्या आप वाकई इसे हटाना चाहते हैं?',
        recordsDeleted: 'रिकॉर्ड सफलतापूर्वक हटा दिए गए',
        updateSuccess: 'सफलतापूर्वक अपडेट किया गया',
        failed: 'अनुरोध संसाधित करने में विफल',
        noResults: 'कोई परिणाम नहीं मिला',
        smsSent: 'एसएमएस रिमाइंडर सफलतापूर्वक भेजा गया',
        collectMonthlyFee: 'मासिक शुल्क जमा करें',
        recordFeePayment: 'छात्र से शुल्क संग्रह रिकॉर्ड करें',
        chooseStudent: 'छात्र चुनें',
        paymentSummary: 'भुगतान सारांश',
        recordPayment: 'भुगतान रिकॉर्ड करें',
        recordingPayment: 'भुगतान रिकॉर्ड हो रहा है...',
        paymentRecorded: 'शुल्क भुगतान सफलतापूर्वक रिकॉर्ड किया गया!',
        month: 'महीना',
        year: 'वर्ष',
        selectMonth: 'महीना चुनें',
        thisMonth: 'इस महीने',
        registerStudentDesc: 'सिस्टम में एक नया छात्र पंजीकृत करें',
        collectFeeDesc: 'छात्रों से मासिक शुल्क संग्रह रिकॉर्ड करें',
        studentListDesc: 'पंजीकृत छात्रों की पूरी सूची देखें',
        schoolsDesc: 'स्कूल देखें और स्कूल द्वारा छात्रों को फ़िल्टर करें',
        monthlyCollectionDesc: 'कुल भुगतान और संग्रह विवरण ट्रैक करें',
        yearlyReportDesc: 'वार्षिक शुल्क संग्रह रिपोर्ट तैयार करें',
        smsRemindersDesc: 'लंबित छात्रों को शुल्क अलर्ट भेजें',
        recentPayments: 'हाल के भुगतान रिकॉर्ड',
        highestPending: 'उच्चतम लंबित शुल्क',
        viewMonthlyReport: 'मासिक रिपोर्ट देखें',
        viewAll: 'सभी देखें',
        aiAnalyticsTitle: 'एआई एनालिटिक्स डैशबोर्ड',
        aiAnalyticsDesc: 'एआई-आधारित अंतर्दृष्टि, भविष्यवाणियां और भुगतान रुझान देखें',
        aiPowered: 'एआई द्वारा संचालित',
        schools: 'स्कूल',
        addSchool: 'स्कूल जोड़ें',
        totalSchools: 'कुल पंजीकृत स्कूल',
        verifiedSchool: 'सत्यापित स्कूल',
        addressOptional: 'पता (वैकल्पिक)',
        contactOptional: 'संपर्क (वैकल्पिक)',
        createSchool: 'स्कूल बनाएं',
        noSchoolsFound: 'कोई स्कूल नहीं मिला। शुरू करने के लिए एक स्कूल जोड़ें।',
        addFirstSchool: 'पहला स्कूल जोड़ें',
        schoolName: 'स्कूल का नाम',
        pendingFeeReminders: 'बकाया शुल्क अनुस्मारक',
        sendSmsAlerts: 'बकाया राशि वाले छात्रों को एसएमएस अलर्ट भेजें',
        sendAllReminders: 'सभी अनुस्मारक भेजें',
        lastReminder: 'पिछला अनुस्मारक',
        sending: 'भेज रहा है...',
        smsSentTo: 'एसएमएस भेजा गया',
        neverSms: 'कभी नहीं',
        editStudentDetails: 'छात्र विवरण संपादित करें',
        fullName: 'पूरा नाम',
        rollNumber: 'रोल नंबर',
        mobileNumber: 'मोबाइल नंबर',
        newPasswordNote: 'नया पासवर्ड (वर्तमान रखने के लिए खाली छोड़ें)',
        updateStudent: 'छात्र अपडेट करें',
        smsRemindersSent: 'एसएमएस अनुस्मारक सफलतापूर्वक भेजे गए',
        sendSmsRemindersAllConfirm: 'सभी छात्रों को एसएमएस अनुस्मारक भेजें?',
        pendingFeesReport: 'बकाया शुल्क रिपोर्ट',
        totalOutstandingBalance: 'कुल बकाया राशि',
        grandTotalPaid: 'कुल भुगतान',
        grandTotalPending: 'कुल बकाया',
        addNewStudent: 'नया छात्र जोड़ें',
        registerStudentDesc: 'एक नया छात्र पंजीकृत करें और उनका क्यूआर कोड अपलोड करें',
        studentAddedSuccess: 'छात्र सफलतापूर्वक जोड़ा गया!',
        failedToAddStudent: 'छात्र जोड़ने में विफल',
        selectClass: 'कक्षा चुनें',
        selectSchool: 'स्कूल चुनें',
        new: 'नया',
        enterNewSchoolName: 'नए स्कूल का नाम दर्ज करें',
        add: 'जोड़ें',
        class: 'कक्षा',
        usernameUserID: 'उपयोगकर्ता नाम (UserID)',
        leaveBlankForMobile: 'मोबाइल नंबर का उपयोग करने के लिए खाली छोड़ें',
        studentQrCode: 'छात्र क्यूआर कोड छवि',
        clickToUploadQr: 'क्यूआर कोड अपलोड करने के लिए क्लिक करें',
        fileFormatNote: 'PNG, JPG या SVG (अधिकतम 2MB)',
        addingStudent: 'छात्र जोड़ रहा है...',
        registerStudent: 'छात्र पंजीकृत करें',
        std6: 'छठी', std7: 'सातवीं', std8: 'आठवीं', std9: 'नौवीं', std10: 'दसवीं',
        yearlyFeeReport: 'वार्षिक शुल्क रिपोर्ट',
        academicYear: 'अकादमिक वर्ष',
        generatedAt: 'जनरेट किया गया',
        reportType: 'रिपोर्ट प्रकार',
        comprehensiveSummary: 'सभी छात्रों का व्यापक सारांश',
        totalYearlyPaid: 'कुल वार्षिक भुगतान',
        monthsCollected: 'महीनों का संग्रह',
        schoolBranding: 'ओम साई स्कूल वैन सर्विस',
        yearlyCollectionGrid: 'वार्षिक संग्रह ग्रिड',
        totalPendingBalance: 'कुल बकाया राशि',
        unpaid: 'अवैतनिक',
        for: 'के लिए',
        totalCount: 'कुल संख्या'
    },
    mr: {
        appName: 'फी व्यवस्थापन',
        logout: 'लॉग आउट',
        dashboard: 'डॅशबोर्ड',
        students: 'विद्यार्थी',
        monthlyCollection: 'मासिक संकलन',
        yearlyReport: 'वार्षिक अहवाल',
        aiAnalytics: 'एआय अअ‍ॅनालिटिक्स',
        smsReminders: 'एसएमएस स्मरणपत्रे',
        addStudent: 'विद्यार्थी जोडा',
        collectFee: 'फी जमा करा',
        pendingFees: 'थकीत फी',
        profile: 'प्रोफाइल',
        edit: 'संपादन',
        search: 'शोधा',
        rollNo: 'हजेरी क्रमांक',
        name: 'नाव',
        class: 'वर्ग',
        mobile: 'मोबाईल',
        amount: 'रक्कम',
        status: 'स्थिती',
        paid: 'भरलेले',
        pending: 'थकीत',
        action: 'कृती',
        backToDashboard: 'डॅशबोर्डवर परत जा',
        welcomeBack: 'पुन्हा स्वागत आहे',
        totalStudents: 'एकूण विद्यार्थी',
        totalCollected: 'एकूण संकलन',
        totalMonthlyCollection: 'एकूण मासिक संकलन',
        avgPayment: 'सरासरी पेमेंट',
        paymentDate: 'पेमेंटची तारीख',
        downloadReport: 'अहवाल डाउनलोड करा',
        exportData: 'डेटा निर्यात करा',
        selectLanguage: 'भाषा निवडा',
        english: 'इंग्रजी',
        hindi: 'हिंदी',
        marathi: 'मराठी',
        admin: 'अअ‍ॅडमिन',
        student: 'विद्यार्थी',
        quickActions: 'त्वरीत कृती',
        reports: 'अहवाल',
        history: 'इतिहास',
        payNow: 'आता फी भरा',
        payFee: 'फी भरा',
        viewProfile: 'प्रोफाइल पहा',
        editProfile: 'प्रोफाइल बदला',
        login: 'लॉगिन',
        overview: 'विद्यार्थी फी व्यवस्थापन प्रणालीचा आढावा',
        viewCompleteFeeRecords: 'तुमचे संपूर्ण फी पेमेंट रेकॉर्ड पहा',
        allStatus: 'सर्व स्थिती',
        paidAmount: 'भरलेली रक्कम',
        pendingAmount: 'थकीत रक्कम',
        totalBalance: 'एकूण थकीत रक्कम',
        allStudents: 'सर्व विद्यार्थी',
        selectStudent: 'विद्यार्थी निवडा',
        school: 'शाळा',
        address: 'पत्ता',
        contact: 'संपर्क',
        actions: 'कृती',
        saveChanges: 'बदल जतन करा',
        cancel: 'रद्द करा',
        fullName: 'पूर्ण नाव',
        enterName: 'विद्यार्थ्याचे नाव प्रविष्ट करा',
        enterRollNo: 'हजेरी क्रमांक प्रविष्ट करा',
        enterMobile: 'मोबाईल क्रमांक प्रविष्ट करा',
        enterPassword: 'पासवर्ड प्रविष्ट करा',
        newPassword: 'नवीन पासवर्ड (जुना ठेवण्यासाठी रिकामे सोडा)',
        studentDetails: 'विद्यार्थी तपशील',
        deleteConfirm: 'तुम्हाला खात्री आहे की तुम्ही हे हटवू इच्छिता?',
        recordsDeleted: 'रेकॉर्ड यशस्वीरित्या हटवले',
        updateSuccess: 'यशस्वीरित्या अपडेट केले',
        failed: 'विनंतीवर प्रक्रिया करण्यात अयशस्वी',
        noResults: 'काहीही आढळले नाही',
        smsSent: 'एसएमएस स्मरणपत्र यशस्वीरित्या पाठवले',
        collectMonthlyFee: 'मासिक फी जमा करा',
        recordFeePayment: 'विद्यार्थ्याची फी भरल्याची नोंद करा',
        chooseStudent: 'विद्यार्थी निवडा',
        paymentSummary: 'पेमेंट सारांश',
        recordPayment: 'पेमेंटची नोंद करा',
        recordingPayment: 'पेमेंटची नोंद होत आहे...',
        paymentRecorded: 'फी पेमेंट यशस्वीरित्या नोंदवले गेले!',
        month: 'महिना',
        year: 'वर्ष',
        selectMonth: 'महिना निवडा',
        thisMonth: 'या महिन्यात',
        registerStudentDesc: 'सिस्टममध्ये नवीन विद्यार्थ्याची नोंदणी करा',
        collectFeeDesc: 'विद्यार्थ्यांकडून मासिक फी भरल्याचे नोंदवा',
        studentListDesc: 'नोंदणीकृत विद्यार्थ्यांची संपूर्ण यादी पहा',
        schoolsDesc: 'शाळा पहा आणि शालेय विद्यार्थ्यांनुसार फिल्टर करा',
        monthlyCollectionDesc: 'एकूण पेमेंट आणि कल ट्रॅक करा',
        yearlyReportDesc: 'वार्षिक फी संकलन अहवाल तयार करा',
        smsRemindersDesc: 'प्रलंबित विद्यार्थ्यांना फी अलर्ट पाठवा',
        recentPayments: 'अलीकडील पेमेंट रेकॉर्ड',
        highestPending: 'सर्वाधिक प्रलंबित फी',
        viewMonthlyReport: 'मासिक अहवाल पहा',
        viewAll: 'सर्व पहा',
        aiAnalyticsTitle: 'AI Analytics Dashboard',
        aiAnalyticsDesc: 'AI-आधारित इनसाइट्स, अंदाज आणि पेमेंट ट्रेंड पहा',
        aiPowered: 'AI वर आधारित',
        schools: 'शाळा',
        addSchool: 'शाळा जोडा',
        totalSchools: 'एकूण नोंदणीकृत शाळा',
        verifiedSchool: 'सत्यापित शाळा',
        addressOptional: 'पत्ता (पर्यायी)',
        contactOptional: 'संपर्क (पर्यायी)',
        createSchool: 'शाळा तयार करा',
        noSchoolsFound: 'कोणतीही शाळा आढळली नाही. सुरू करण्यासाठी एक शाळा जोडा.',
        addFirstSchool: 'पहिली शाळा जोडा',
        schoolName: 'शाळेचे नाव',
        pendingFeeReminders: 'थकीत शुल्क आठवण',
        sendSmsAlerts: 'थकीत रक्कम असलेल्या विद्यार्थ्यांना SMS अलर्ट पाठवा',
        sendAllReminders: 'सर्व आठवणी पाठवा',
        lastReminder: 'शेवटची आठवण',
        sending: 'पाठवत आहे...',
        smsSentTo: 'SMS पाठवला',
        neverSms: 'कधीही नाही',
        editStudentDetails: 'विद्यार्थ्याची माहिती संपादित करा',
        fullName: 'पूर्ण नाव',
        rollNumber: 'रोल नंबर',
        mobileNumber: 'मोबाईल नंबर',
        newPasswordNote: 'नवीन पासवर्ड (जुना ठेवण्यासाठी रिकामे सोडा)',
        updateStudent: 'विद्यार्थी अपडेट करा',
        smsRemindersSent: 'SMS आठवण यशस्वीरित्या पाठवली गेली',
        sendSmsRemindersAllConfirm: 'सर्व विद्यार्थ्यांना SMS आठवण पाठवायची का?',
        pendingFeesReport: 'थकीत शुल्क अहवाल',
        totalOutstandingBalance: 'एकूण थकीत रक्कम',
        grandTotalPaid: 'एकूण भरलेले शुल्क',
        grandTotalPending: 'एकूण थकीत शुल्क',
        addNewStudent: 'नवीन विद्यार्थी जोडा',
        registerStudentDesc: 'नवीन विद्यार्थ्याची नोंदणी करा आणि त्यांचा QR कोड अपलोड करा',
        studentAddedSuccess: 'विद्यार्थी यशस्वीरित्या जोडला गेला!',
        failedToAddStudent: 'विद्यार्थी जोडता आला नाही',
        selectClass: 'इयत्ता निवडा',
        selectSchool: 'शाळा निवडा',
        new: 'नवीन',
        enterNewSchoolName: 'नवीन शाळेचे नाव टाका',
        add: 'जोडा',
        class: 'इयत्ता',
        usernameUserID: 'युजरनेम (UserID)',
        leaveBlankForMobile: 'मोबाईल नंबर वापरण्यासाठी रिकामे सोडा',
        studentQrCode: 'विद्यार्थी QR कोड फोटो',
        clickToUploadQr: 'QR कोड अपलोड करण्यासाठी क्लिक करा',
        fileFormatNote: 'PNG, JPG किंवा SVG (जास्तीत जास्त 2MB)',
        addingStudent: 'विद्यार्थी जोडत आहे...',
        registerStudent: 'विद्यार्थी नोंदणी करा',
        std1: 'पहिली', std2: 'दुसरी', std3: 'तिसरी', std4: 'चौथी', std5: 'पाचवी',
        std6: 'सहावी', std7: 'सातवी', std8: 'आठवी', std9: 'नववी', std10: 'दहावी',
        yearlyFeeReport: 'वार्षिक शुल्क अहवाल',
        academicYear: 'शैक्षणिक वर्ष',
        generatedAt: 'तयार केला',
        reportType: 'अहवाल प्रकार',
        comprehensiveSummary: 'सर्व विद्यार्थ्यांचा सारांश',
        totalYearlyPaid: 'एकून वार्षिक भरलेले शुल्क',
        monthsCollected: 'महिने जमा झाले',
        schoolBranding: 'ओम साई स्कूल व्हॅन सर्विस',
        yearlyCollectionGrid: 'वार्षिक संकलन ग्रिड',
        totalPendingBalance: 'एकून थकीत रक्कम',
        unpaid: 'अवैतनिक',
        for: 'साठी',
        totalCount: 'एकूण संख्या'
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('preferredLanguage') || 'en');

    useEffect(() => {
        localStorage.setItem('preferredLanguage', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    const tEn = (key) => {
        return translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, tEn }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
